In [1]:


import numpy as np



In [ ]:
You are given the following data of student marks in a 5-by-5 matrix. 

|  id | Assignment 1 score | Assignment 2 score | Total score | Score percentage |     
| --- | ------------------ | ------------------ | ----------- | ---------------- |     
|   1 |                 12 |                 19 |          31 |             0.62 |     
|   2 |                 20 |                 21 |          41 |             0.82 |     
|   3 |                 15 |                 22 |          37 |             0.74 |     
|   4 |                 14 |                  9 |          23 |             0.46 |     
|   5 |                 25 |                 25 |          50 |             1.00 | 

 a. Use the column names (not the data values) to make a guess of the rank of the matrix. Explain your guess.   
Total score = Assignment 1 score + Assignment 2 
score  percent = Total score / 100 
You can remove the last two columns without losing any data. The rank of the matrix is 3 (since there are three columns remaining).


In [ ]:
b. Use one of the analytical techniques or algorithms we have learned to verify your guess. For your convenience, here's the data in csv format: 
1,12,19,31,0.62         
2,20,21,41,0.82         
3,15,22,37,0.74         
4,14,9,23,0.46         
5,25,25,50,1.00

a = np.genfromtxt('filename.csv', delimiter=',') 
u, s, v = np.linalg.svd(a)
Look at the s list. It should have length 5 and the last two should be essential zero. There are 3 remaining, thus the rank of the matrix is 3.


In [2]:
a = np.genfromtxt('/Users/chidam/Desktop/svd_csvfile.csv', delimiter=',')

In [3]:
u, s, v = np.linalg.svd(a)

In [10]:
s

array([1.03052540e+02, 7.47566048e+00, 2.02593956e+00, 1.41282085e-15,
       3.43356444e-16])

In [5]:
len(s)

5

In [6]:
u

array([[-0.36970006, -0.53233823,  0.10964768, -0.11834758, -0.7442507 ],
       [-0.48752232,  0.06445049,  0.75523635, -0.25778256,  0.34833078],
       [-0.44209637, -0.4360889 , -0.55913225, -0.25033332,  0.48895974],
       [-0.27405986,  0.65823946, -0.29414729, -0.56770978, -0.28774119],
       [-0.5958908 ,  0.29834447, -0.13580849,  0.73115035, -0.05366507]])

In [7]:
len(u)

5

In [8]:
v

array([[-6.54688107e-02, -3.83808110e-01, -4.30384332e-01,
        -8.14192442e-01, -1.62838488e-02],
       [ 3.22777669e-01,  6.73329379e-01, -6.65112455e-01,
         8.21692388e-03,  1.64338478e-04],
       [-9.44207822e-01,  2.56790023e-01, -1.97527169e-01,
         5.92628541e-02,  1.18525708e-03],
       [ 0.00000000e+00,  5.77373636e-01,  5.77373636e-01,
        -5.76998112e-01, -1.87762189e-02],
       [-0.00000000e+00, -4.17729779e-03, -4.17729779e-03,
         2.41711054e-02, -9.99690381e-01]])

In [9]:
len(v)

5

In [ ]:
You are testing a new version of your website. You randomly partition your users into 2 groups. Group A continues to get the old version of the website. Group B gets the new version of the website. You would like to maximize the number of registrations. These are the results you get:      
| Group | Viewers | Registrations |     
| ----- 	| ------- | ------------- |     
|     A 	|     612 |           103 |     
|     B 	|     595 |           144 |      
Can we say with confidence that the new version of the website is better?


In [11]:
Define the hypothesis:
H0:that the new version is not better
H1:the new version is better

The contingency table is as follows:

Group Registered Did not Register
A          103      509
B          144      451
You can use scipy chi squared test:

from scipy.stats import chi2_contingency
chi2, p, dof, expected = chi2_contingency([[103, 509], [144, 451]], correction=False)
print ("p-value:{}".format(p/2))




p-value:0.0007525358465393692


In [ ]:
The approx. p_value is 0.00075 which is way less than the critical value at 95% confidence level: alpha=0.05 to be considered significant
therefore we reject H0
The observed conversion rate for Group A is 103/612=16.8%. The observed conversion rate for Group B is 144/595=24.2%.

We conclude that site B is superior.
